export const randomItems = [
    "Apple", "Dog", "Laptop", "Coffee", "France",
    "Sunglasses", "Bicycle", "Book", "Banana", "Orange",
    "Cat", "Smartphone", "Tea", "Germany", "Watch",
    "Running Shoes", "Magazine", "Grapes", "Pear", "Bird",
    "Headphones", "Juice", "Italy", "Backpack", "Tennis Racket",
    "Novel", "Watermelon", "Strawberry", "Fish", "Desktop Computer",
    "Soda", "Spain", "Necklace", "Golf Clubs", "Comic Book",
    "Pineapple", "Lemon", "Turtle", "Tablet", "Beer",
    "Japan", "Earrings", "Soccer Ball", "Cookbook", "Cherry",
    "Water", "Elephant", "Camera", "Milk", "Brazil",
    "Bracelet", "Basketball", "DVD", "Kiwi", "Mango",
    "Horse", "Printer", "Wine", "Australia", "Ring",
    "Baseball Bat", "Notebook", "Cucumber", "Potato", "Lion",
    "Speaker", "Whiskey", "China", "Scarf", "Football",
    "Sketchbook", "Avocado", "Peach", "Giraffe", "Microphone",
    "Coffee Maker", "India", "Hat", "Hiking Boots", "Calendar",
    "Olive Oil", "Onion", "Zebra", "Projector", "Chocolate",
    "Bread", "Kangaroo", "Keyboard", "Smoothie", "Russia",
    "Purse", "Treadmill", "Board Game", "Blackberries", "Rice",
    "Ostrich", "Projector Screen", "Ice Cream", "Canada", "Cufflinks",
    "Hiking Backpack", "Easel", "Tomato", "Cabbage", "Penguin",
    "Graphics Card", "Hot Chocolate", "Mexico", "Wallet", "Swimming Goggles",
    "MP3 Player", "Plum", "Walnut", "Rhinoceros", "Webcam",
    "Tequila", "South Africa", "Tie", "Jump Rope", "Oil Paints",
    "Apricot", "Lettuce", "Crocodile", "GPS Navigator", "Cocktail",
    "New Zealand", "Gloves", "Snowboard", "Watercolor Paints", "Pomegranate",
    "Broccoli", "Monkey", "External Hard Drive", "Lemonade", "South Korea",
    "T-Shirt", "Dumbbells", "Candle", "Peanut Butter", "Corn",
    "Gorilla", "Smart Watch", "Sushi", "Argentina", "Sandals",
    "Tent", "Sketch Pens", "Mango Juice", "Potato Chips", "Owl",
    "Drone", "Smoothie Maker", "Thailand", "Sunglasses Case", "Bicycle Helmet",
    "Stroller", "Gin", "Switzerland", "Perfume", "Ski Boots",
    "Binoculars", "Champagne", "Portugal", "Hairbrush", "Soccer Cleats",
    "Travel Guide", "Bacon", "Turkey", "Seal", "Laser Printer",
    "Espresso Machine", "Ireland", "Earrings Box", "Roller Skates", "Fountain Pen",
    "Cranberries", "Strawberry cheesecake", "Shrimp alfredo", "Caesoh",
    "Mcnuggets", "Skibidi slicers", "Halo breach", "Master Cheif", "Skibidi toilet",
];
